trigger:
- main
- develop
- feature/*

pool: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'package'

- task: Docker@2
  inputs:
    containerRegistry: 'cryptobotpublic-bsn-group'
    repository: 'bsngroup/analyzer'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.SourceVersion)